import type { Component } from 'vue'
import {
  Archive,
  Atom,
  BadgeAlert,
  BarChart3,
  Bot,
  Box,
  Boxes,
  BrickWall,
  BriefcaseBusiness,
  Building2,
  CircleAlert,
  CircleDotDashed,
  CircleGauge,
  Clock,
  Cloud,
  Columns3,
  Coins,
  Columns4,
  Crosshair,
  Dna,
  Download,
  Factory,
  FileDown,
  FileUp,
  Flame,
  Gem,
  Globe,
  Globe2,
  HandCoins,
  Handshake,
  HeartPulse,
  Hammer,
  Landmark,
  Layers,
  ListPlus,
  Lock,
  MapPinned,
  Monitor,
  Mountain,
  Orbit,
  Pause,
  Play,
  RefreshCcw,
  Rocket,
  Route,
  Save,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Skull,
  Smile,
  Sparkles,
  Sprout,
  MessageSquareText,
  Pickaxe,
  Swords,
  Trees,
  Trophy,
  Trash2,
  Umbrella,
  Users,
  WandSparkles,
  X,
  Zap,
} from '@lucide/vue'

export const iconMap = {
  achievement: Trophy,
  arpa: Landmark,
  blackholeReset: CircleDotDashed,
  bioseedReset: Sprout,
  cataclysmReset: Mountain,
  city: Building2,
  civic: BriefcaseBusiness,
  clock: Clock,
  cloudReset: Cloud,
  coins: Coins,
  columns: Columns4,
  crispr: Atom,
  crosshair: Crosshair,
  customRace: SlidersHorizontal,
  dangerAlert: BadgeAlert,
  descendReset: Flame,
  download: Download,
  edenic: Sparkles,
  edenReset: Trees,
  evolution: Dna,
  flame: Flame,
  fileDown: FileDown,
  fileUp: FileUp,
  galaxy: Orbit,
  governor: CircleGauge,
  handCoins: HandCoins,
  handshake: Handshake,
  hammer: Hammer,
  heartPulse: HeartPulse,
  industry: Hammer,
  factory: Factory,
  landmark: Landmark,
  layers: Layers,
  lock: Lock,
  madReset: CircleAlert,
  magic: WandSparkles,
  market: Globe2,
  mapPinned: MapPinned,
  mech: Bot,
  military: Swords,
  messages: MessageSquareText,
  mining: Pickaxe,
  matrixReset: Monitor,
  monumentBrick: BrickWall,
  monumentColumns: Columns3,
  monumentGem: Gem,
  monumentStone: Box,
  portal: Flame,
  pause: Pause,
  play: Play,
  prestige: RefreshCcw,
  queue: ListPlus,
  races: Users,
  retireReset: Umbrella,
  resources: Boxes,
  route: Route,
  save: Save,
  shieldCheck: ShieldCheck,
  smile: Smile,
  sparkles: Sparkles,
  space: Rocket,
  stats: BarChart3,
  storage: Archive,
  terraformReset: Globe,
  truepath: Shield,
  trash: Trash2,
  vacuumReset: Skull,
  womling: Factory,
  settings: Settings,
  users: Users,
  close: X,
  zap: Zap,
} as const satisfies Record<string, Component>

export type IconName = keyof typeof iconMap
