/**
 * 资源 ID → 中文名映射
 */
export const RESOURCE_NAMES: Record<string, string> = {
  Money: '金币',
  Food: '食物',
  Lumber: '木材',
  Stone: '石头',
  Furs: '毛皮',
  Copper: '铜',
  Iron: '铁',
  Cement: '水泥',
  Coal: '煤',
  Knowledge: '知识',
  Faith: '信仰',
  Steel: '钢',
  Aluminium: '铝',
  Oil: '石油',
  Titanium: '钛',
  Uranium: '铀',
  Plywood: '胶合板',
  Brick: '砖',
  Wrought_Iron: '锻铁',
  Sheet_Metal: '金属板',
  Alloy: '合金',
  Polymer: '聚合物',
  Crates: '板条箱',
  Containers: '集装箱',
  RNA: 'RNA',
  DNA: 'DNA',
  Mana: '魔力',
  Crystal: '水晶',
  Iridium: '铱',
  Helium_3: '氦-3',
  Elerium: '超铀',
  Neutronium: '中子素',
  Mythril: '秘银',
  Nano_Tube: '纳米管',
  Adamantite: '精金',
  Stanene: '锡烯',
  Soul_Gem: '灵魂宝石',
  Demonic_Essence: '恶魔精华',
  Codex: '法典',
  Infernite: '炼狱矿',
  Sus: '疑虑',
  Asphodel_Powder: '阿斯福德尔粉末',
  Ectoplasm: '幽质',
  Elysanite: '极乐石',
  Omniscience: '全知',
  Hydrogen: '氢',
  Oxygen: '氧',
  Water: '水',
  Orichalcum: '黄金矿',
  Quantium: '量子素',
  Bolognium: '博洛尼亚合金',
  Vitreloy: '玻璃合金',
  Aerogel: '气凝胶',
  Nanoweave: '纳米织物',
  Scarletite: '猩红石',
  Deuterium: '氘',
  Graphene: '石墨烯',
  Chrysotile: '温石棉',
  Blood_Stone: '血石',
  Corrupt_Gem: '腐败宝石',
}

/** 获取资源中文名 */
export function getResourceName(id: string): string {
  return RESOURCE_NAMES[id] ?? id
}
