/** Generated from legacy/strings/strings.zh-CN.json and legacy/src/achieve.js. */
export interface AchievementLocaleText {
  name: string;
  desc: string;
  flair: string;
}

export const ACHIEVEMENT_LOCALE: Record<string, AchievementLocaleText> = {
  "apocalypse": {"name":"启示录","desc":"使用核武器灭绝自己。","flair":"不好，避难所出故阝"},
  "ascended": {"name":"飞升","desc":"进行飞升重置，前往更高阶的位面。","flair":"逆天改命，变成光吧！"},
  "dreaded": {"name":"可畏","desc":"进行飞升重置时未拥有无畏舰。","flair":"才不是什么肥恐龙啦！"},
  "anarchist": {"name":"无政府主义者","desc":"在无政府体制下进行核爆重置。","flair":"有些人只想看到这个世界燃烧。"},
  "second_evolution": {"name":"二次进化","desc":"连续两次进化成同一种族，然后研究狂热信仰。","flair":"是巧合，还是古老的狂妄自大？"},
  "blackhole": {"name":"黑洞非洞","desc":"人工制造黑洞，且没有因此摧毁你的行星。","flair":"懂科学，就无需恐惧。"},
  "warmonger": {"name":"成吉思汗的继承人","desc":"使战争贩子惩罚不低于 8%。","flair":"生活中最好的事是什么？自然是看着敌人倒在你面前。"},
  "red_tactics": {"name":"红色战术家","desc":"在本周目游戏中有 250 名士兵阵亡。","flair":"我们已无路可退，身后就是家园！"},
  "pacifist": {"name":"和平主义者","desc":"本周目游戏未发起过进攻的前提下统一世界。","flair":"要有爱！不要战争！"},
  "neutralized": {"name":"消灭","desc":"彻底控制仙女座星云的威胁。","flair":"斩草除根，赶尽杀绝"},
  "paradise": {"name":"乐土","desc":"将士气提升至 200%。","flair":"别担心，开心点。"},
  "scrooge": {"name":"守财奴","desc":"资金达到 $1000M。","flair":"可别在这里面游泳。"},
  "madagascar_tree": {"name":"马达加斯加树","desc":"进化成噩梦般的食肉树。","flair":"奥黛丽三世"},
  "godwin": {"name":"高德温法则","desc":"使用有毒的巨魔研究互联网。","flair":"9岁上网的玩梗小鬼。"},
  "laser_shark": {"name":"激光鲨鱼","desc":"创造出能够发射激光的鲨鱼。","flair":"一定是什么邪恶博士的作品吧？"},
  "infested": {"name":"受感染的人类","desc":"使用精神控制的寄生虫感染人类。","flair":"为了母巢！"},
  "mass_starvation": {"name":"大倒退","desc":"在本周目游戏中饿死 100 位市民。","flair":"胡弗是你的导师吗？"},
  "colonist": {"name":"太空定居者","desc":"定居到另一个星球。","flair":"这是殖民者的一小步……"},
  "world_domination": {"name":"统治世界","desc":"只通过军事力量征服世界。","flair":"这些风险游戏终究获得了回报。"},
  "illuminati": {"name":"光明会","desc":"只通过影响力攫取世界的控制权。","flair":"藏身于幕后，操控一切。"},
  "syndicate": {"name":"辛迪加","desc":"只利用财富收购整个世界。","flair":"概不退换，购者自慎。"},
  "cult_of_personality": {"name":"个人崇拜","desc":"拒绝统一，用领导能力激励人民。","flair":"再好的武器，也得在人的手里才能发挥作用。"},
  "doomed": {"name":"毁灭战士","desc":"阻止地狱的入侵。","flair":"射它，射到死为止！"},
  "pandemonium": {"name":"群魔乱舞","desc":"建造堡垒，以阻挡地狱的攻势。","flair":"君且安坐，听我一言。"},
  "blood_war": {"name":"血战","desc":"加入恶魔之间永不休止的古老战争。","flair":"一星不容二魔。"},
  "landfill": {"name":"星系垃圾填埋场","desc":"使用质量喷射器将黑洞质量扩充到 12 个太阳质量。","flair":"每位星系霸主都会这么对待黑洞的，这我敢肯定。"},
  "seeder": {"name":"播种者","desc":"对外星世界进行播种。","flair":"神明，舍我其谁？"},
  "miners_dream": {"name":"主矿脉","desc":"在至少有 4 条矿产属性为丰富的星球上达到伟大。","flair":"既入宝山，焉能空手而归！"},
  "shaken": {"name":"手摇，不要搅拌","desc":"引起大灾变。","flair":"都怪他们没给世界对撞机贴上警告标志！"},
  "blacken_the_sun": {"name":"遮蔽太阳","desc":"将戴森球升级到最大。","flair":"你所有的光亮都属于我们。"},
  "trade": {"name":"贸易联邦","desc":"在联邦体制下，同时激活 750 条贸易路线和 50 条星贸路线。","flair":"我们的贸易封锁是完全合法的。"},
  "resonance": {"name":"共振","desc":"让你的种族加入多元宇宙。","flair":"感受到能量了吗？"},
  "enlightenment": {"name":"启蒙","desc":"每个种群都至少有一个种族加入多元宇宙。","flair":"五十个种族，五十枝花；五十个兄弟姐妹是一家。"},
  "gladiator": {"name":"角斗士","desc":"击败尖塔中的每一种首领。","flair":"你们看爽了没？"},
  "corrupted": {"name":"腐化","desc":"成为恶魔领主。","flair":"你甚至都不需要去做浮士德式交易。"},
  "red_dead": {"name":"尚未燃起的星星之火","desc":"在未开发红色行星的前提下，摧毁宇宙。","flair":"潜龙于渊，涉灵愈伤，千里一怒，红莲灿世。"},
  "godslayer": {"name":"弑神者","desc":"征服天堂。","flair":"旧的不去，新的不来。"},
  "traitor": {"name":"叛逆者","desc":"背叛天堂的誓言。","flair":"新官上任。"},
  "doppelganger": {"name":"替身","desc":"干掉您的尖塔替身。","flair":"我到底该指向哪个发射目标？"},
  "mass_extinction": {"name":"大灭绝","desc":"毁灭 25 个不同种族的文明。","flair":"宇宙射线对你毫无影响。"},
  "extinct_human": {"name":"已亡人","desc":"毁灭人类文明。","flair":"直立人？更像软弱人。"},
  "extinct_elven": {"name":"又稀少，又高傲，还作死……","desc":"毁灭精灵文明。","flair":"至少还是可以当肥料用的。"},
  "extinct_orc": {"name":"外域难民","desc":"毁灭兽人文明。","flair":"荣耀之光熄灭了。"},
  "extinct_cath": {"name":"剑齿虎","desc":"毁灭猫族文明。","flair":"抓破了最后一根柱子。"},
  "extinct_wolven": {"name":"恐狼","desc":"毁灭狼人文明。","flair":"独余明月照江流。"},
  "extinct_vulpine": {"name":"猎狐行动","desc":"毁灭妖狐文明。","flair":"关门放狗！"},
  "extinct_centaur": {"name":"汗血宝马","desc":"毁灭半人马文明。","flair":"腾蛇乘雾，终为土灰。"},
  "extinct_rhinotaur": {"name":"偷猎者","desc":"毁灭犀牛文明。","flair":"传统医学，传统灭绝。"},
  "extinct_capybara": {"name":"捕鼠器","desc":"毁灭水豚文明。","flair":"道理我都懂，可是这水豚为什么这么大？"},
  "extinct_kobold": {"name":"蜡烛被抢走了","desc":"毁灭狗头人文明。","flair":"闻起来味道不太好。"},
  "extinct_goblin": {"name":"贪得无厌","desc":"毁灭哥布林文明。","flair":"这墓碑太便宜了。"},
  "extinct_gnome": {"name":"躺平","desc":"毁灭侏儒文明。","flair":"反正也跑不过炸弹。"},
  "extinct_ogre": {"name":"笨死的","desc":"毁灭食人魔文明。","flair":"达尔文点了个赞。"},
  "extinct_cyclops": {"name":"盲目的野心","desc":"毁灭独眼巨人文明。","flair":"失去了唯一的眼睛。"},
  "extinct_troll": {"name":"咒符坏了","desc":"毁灭巨魔文明。","flair":"支付了最后的通行费。"},
  "extinct_tortoisan": {"name":"生命的循环","desc":"毁灭乌龟人文明。","flair":"一只海龟入水失败。"},
  "extinct_gecko": {"name":"没省多少","desc":"毁灭壁虎人文明。","flair":"利率可没他们宣传的那么好。"},
  "extinct_slitheryn": {"name":"最后一次蜕皮","desc":"毁灭娜迦文明。","flair":"被苹果噎死了。"},
  "extinct_arraak": {"name":"渡渡鸟的覆辙","desc":"毁灭陆行鸟文明。","flair":"鸡肉味，嘎嘣脆。"},
  "extinct_pterodacti": {"name":"希克苏鲁伯","desc":"毁灭翼手龙文明。","flair":"不适者淘汰。"},
  "extinct_dracnid": {"name":"孤寂的史矛革","desc":"毁灭天龙文明。","flair":"孤山要永远荒凉下去了。"},
  "extinct_entish": {"name":"萨鲁曼的复仇","desc":"毁灭树人文明。","flair":"统统放倒。"},
  "extinct_cacti": {"name":"沙漠啥都殁了","desc":"毁灭仙人掌文明。","flair":"绿洲终究是海市蜃楼。"},
  "extinct_pinguicula": {"name":"除草机","desc":"毁灭捕虫堇文明。","flair":"从历史的长河中连根拔起。"},
  "extinct_sporgar": {"name":"杀真菌剂","desc":"毁灭孢子虫文明。","flair":"未来的石油。"},
  "extinct_shroomi": {"name":"磕嗨坠机","desc":"毁灭蘑菇人文明。","flair":"为什么我不洁身自好呢？"},
  "extinct_moldling": {"name":"消化","desc":"毁灭霉菌人文明。","flair":"成为同族的饲料。"},
  "extinct_mantis": {"name":"没有回应的祈祷","desc":"毁灭螳螂人文明。","flair":"也许下次他们会听到。"},
  "extinct_scorpid": {"name":"普莫诺蝎","desc":"毁灭蝎子人文明。","flair":"猫头鹰万岁！"},
  "extinct_antid": {"name":"偏侧蛇虫草菌","desc":"毁灭蚂蚁人文明。","flair":"成为历史。"},
  "extinct_sharkin": {"name":"巨齿鲨","desc":"毁灭鲨鱼人文明。","flair":"这是您点的鱼翅汤。"},
  "extinct_octigoran": {"name":"炸鱿鱼圈","desc":"毁灭八爪鱼文明。","flair":"大卸八块，然后下油锅。"},
  "extinct_dryad": {"name":"尘归尘","desc":"毁灭树妖文明。","flair":"敌袭！"},
  "extinct_satyr": {"name":"万籁此俱寂","desc":"毁灭萨提尔文明。","flair":"沉默是金。"},
  "extinct_phoenix": {"name":"熄灭","desc":"毁灭不死鸟文明。","flair":"凉透了。"},
  "extinct_salamander": {"name":"冷却完毕","desc":"毁灭火蜥蜴文明。","flair":"火萎了，我也准备走了。"},
  "extinct_yeti": {"name":"捕获","desc":"毁灭雪怪文明。","flair":"最终还是被拍到了。"},
  "extinct_wendigo": {"name":"无魂憎恶","desc":"毁灭温迪戈文明。","flair":"灵魂吃完了。"},
  "extinct_tuskin": {"name":"吓一跳","desc":"毁灭塔斯肯文明。","flair":"实在是受不了了。"},
  "extinct_kamel": {"name":"找不到绿洲","desc":"毁灭骆驼人文明。","flair":"水喝完了。"},
  "extinct_balorg": {"name":"自焚","desc":"毁灭炎魔文明。","flair":"像那条龙一样燃烧。"},
  "extinct_imp": {"name":"与恶魔交易","desc":"毁灭小恶魔文明。","flair":"为最后一任主人服务。"},
  "extinct_seraph": {"name":"天使之落","desc":"毁灭大天使文明。","flair":"你并没有堕落，只是因核弹头而陨落了。"},
  "extinct_unicorn": {"name":"独角兽汉堡","desc":"毁灭独角兽文明。","flair":"尝尝彩虹！"},
  "extinct_synth": {"name":"不值钱的仿制品","desc":"毁灭合成人文明。","flair":"一堆劣质的货色。"},
  "extinct_nano": {"name":"自噬","desc":"毁灭纳米机器人文明。","flair":"饥不择食。"},
  "extinct_ghast": {"name":"幽灵消亡","desc":"毁灭妖鬼文明。","flair":"谁开了灯？"},
  "extinct_shoggoth": {"name":"只是工具而已","desc":"毁灭修格斯文明。","flair":"用后即弃。"},
  "extinct_dwarf": {"name":"矿井塌陷","desc":"毁灭矮人文明。","flair":"挖的太深以至于挖到用不到东西了……"},
  "extinct_raccoon": {"name":"钥匙遗失","desc":"毁灭浣熊人文明。","flair":"偷东西太多，被捕捉了……"},
  "extinct_lichen": {"name":"无法兼容","desc":"毁灭地衣人文明。","flair":"共生关系不够稳固。"},
  "extinct_wyvern": {"name":"似龙非龙","desc":"毁灭双足飞龙文明。","flair":"还需要长出更多的腿。"},
  "extinct_beholder": {"name":"眼睛干涩","desc":"毁灭眼魔文明。","flair":"只是一个干枯的眼球而已。"},
  "extinct_djinn": {"name":"困于神灯中","desc":"毁灭灯神文明。","flair":"哦？"},
  "extinct_narwhal": {"name":"角断了","desc":"毁灭独角鲸文明。","flair":"你这样做，不是会变成白鲸吗？"},
  "extinct_bombardier": {"name":"炸平了","desc":"毁灭炮弹虫文明。","flair":"弹药耗尽。"},
  "extinct_nephilim": {"name":"与神同死","desc":"毁灭奈非天文明。","flair":"谬误已被清除。"},
  "extinct_junker": {"name":"安乐死","desc":"结束瓦尔迪的痛苦。","flair":"达尔文会同意的。"},
  "extinct_sludge": {"name":"柠檬清洁剂","desc":"结束软泥的痛苦。","flair":"再多来点清洁剂。"},
  "extinct_ultra_sludge": {"name":"终极污渍","desc":"清理终极软泥。","flair":"污渍恐怕永远清理不掉……"},
  "extinct_custom": {"name":"实验室故障","desc":"毁灭自定义种族。","flair":"下个版本一定会修复的！下次一定！"},
  "extinct_hybrid": {"name":"失败的混合体","desc":"毁灭自定义混合种族。","flair":"下次应该换一种不一样的配方了。"},
  "creator": {"name":"造物主","desc":"引领 9 个不同的种群将自身传承下去。","flair":"有形之物，终会腐朽。无形之物，代代相传。"},
  "genus_humanoid": {"name":"人类必胜","desc":"引领类人文明走向伟大。","flair":"我们的征途是星辰大海。"},
  "genus_carnivore": {"name":"闻星识迹","desc":"引领食肉动物文明走向伟大。","flair":"追踪猎物，直到宇宙的尽头。"},
  "genus_herbivore": {"name":"素食主义","desc":"引领食草动物文明走向伟大。","flair":"动物救星还是植物杀手？"},
  "genus_small": {"name":"小个子的霸权","desc":"引领矮人文明走向伟大。","flair":"你证明了大小并不重要。"},
  "genus_giant": {"name":"总是大一号","desc":"引领巨人文明走向伟大。","flair":"你证明了大小确实重要。"},
  "genus_reptilian": {"name":"飞向太阳","desc":"引领爬行动物文明走向伟大。","flair":"再也不会被冷落。"},
  "genus_avian": {"name":"翱翔天际","desc":"引领翼类文明走向伟大。","flair":"连不会飞的鸟也上天了。"},
  "genus_insectoid": {"name":"无限繁殖","desc":"引领昆虫文明走向伟大。","flair":"只不过是数字游戏而已。"},
  "genus_plant": {"name":"无限生长","desc":"引领植物文明走向伟大。","flair":"在土壤中傲然挺立。"},
  "genus_fungi": {"name":"风中的孢子","desc":"引领菌类文明走向伟大。","flair":"到处传播，连星辰也一样！"},
  "genus_aquatic": {"name":"天堂水族馆","desc":"引领水生生物文明走向伟大。","flair":"遨游星海。"},
  "genus_fey": {"name":"这不是迪斯尼！","desc":"引领精怪文明走向伟大。","flair":"真是一个童话般的结局。"},
  "genus_heat": {"name":"酷热","desc":"引领烈焰文明走向伟大。","flair":"你恐怕是呆在了厨房里。"},
  "genus_polar": {"name":"极地涡流","desc":"引领极地文明走向伟大。","flair":"连个会说话的雪人都没有。"},
  "genus_sand": {"name":"沙暴幸存者","desc":"引领沙漠文明走向伟大。","flair":"沙漠吞噬了一切……但却对你无可奈何。"},
  "genus_demonic": {"name":"燃烧的远征","desc":"引领恶魔文明走向伟大。","flair":"无数个世界都将陷入火海。"},
  "genus_angelic": {"name":"黑暗中的光明","desc":"引领天堂文明走向伟大。","flair":"你是这个扭曲宇宙的希望之光。"},
  "genus_synthetic": {"name":"智械觉醒","desc":"引领机械文明走向伟大。","flair":"2.0 版本启动。"},
  "genus_eldritch": {"name":"拥抱疯狂","desc":"引领异魔文明走向伟大。","flair":"赞颂吾名，亦或陨灭。"},
  "explorer": {"name":"韦拉扎诺","desc":"至少在 6 个不同生物群系的星球上分别进行播种重置。","flair":"恭喜你没在半路上被食人族吃掉。"},
  "biome_grassland": {"name":"草原开化者","desc":"在草原星球上建立文明。","flair":"你自己建设的花园世界。"},
  "biome_oceanic": {"name":"海洋开化者","desc":"在海洋星球上建立文明。","flair":"漂浮在宇宙中的蓝色宝石。"},
  "biome_forest": {"name":"森林开化者","desc":"在森林星球上建立文明。","flair":"森林乐土对你敞开了大门。"},
  "biome_desert": {"name":"沙漠开化者","desc":"在沙漠星球上建立文明。","flair":"驯服了无情的沙漠，现在它是你的形状了。"},
  "biome_volcanic": {"name":"火山开化者","desc":"在火山星球上建立文明。","flair":"原初世界的主人。"},
  "biome_tundra": {"name":"苔原开化者","desc":"在苔原星球上建立文明。","flair":"寒冷从未让你困扰过。"},
  "biome_savanna": {"name":"稀树开化者","desc":"在稀树星球上建立文明。","flair":"祈求甘霖，降于此地。"},
  "biome_swamp": {"name":"沼泽开化者","desc":"在沼泽星球上建立文明。","flair":"大概就是，某个爱洗澡的小……"},
  "biome_ashland": {"name":"灰幕开化者","desc":"在灰幕星球上建立文明。","flair":"用X渍，没污渍！"},
  "biome_taiga": {"name":"针叶林开化者","desc":"在针叶林星球上建立文明。","flair":"并不是什么魔法森林。"},
  "biome_hellscape": {"name":"地狱来客","desc":"在地狱星球上建立文明。","flair":"再也不用呆在伦敦了！"},
  "biome_eden": {"name":"失乐园","desc":"在伊甸星球上建立文明。","flair":"令人惊讶的是，这里几乎没有花园。"},
  "atmo_toxic": {"name":"超级基金法","desc":"在毒气星球上建立文明。","flair":"环保局已经放弃了。"},
  "atmo_mellow": {"name":"潮湿","desc":"在温和星球上建立文明。","flair":"氮原子是空气的主要组成部分。"},
  "atmo_rage": {"name":"重装步兵","desc":"在愤怒星球上建立文明。","flair":"这就是斯巴达！"},
  "atmo_stormy": {"name":"长篇大论","desc":"在风暴星球上建立文明。","flair":"闭嘴！"},
  "atmo_ozone": {"name":"空洞","desc":"在缺乏臭氧的星球上建立文明。","flair":"防晒指数需要达到一百万。"},
  "atmo_magnetic": {"name":"万磁星","desc":"在磁性星球上建立文明。","flair":"你在期待一个戴红头盔的人吗？"},
  "atmo_trashed": {"name":"鲁弗斯","desc":"在垃圾星球上建立文明。","flair":"终究没能到达伊利瑟姆。"},
  "atmo_elliptical": {"name":"夏季之子","desc":"在椭圆星球上建立文明。","flair":"凛冬将至。"},
  "atmo_flare": {"name":"烤焦了","desc":"在耀斑灾害频发的星球上建立文明。","flair":"零星，不推荐。"},
  "atmo_dense": {"name":"迟钝","desc":"在高密度星球上建立文明。","flair":"思 考 停 止"},
  "atmo_unstable": {"name":"摇啊摇","desc":"在地震星球上建立文明。","flair":"我飘啊飘。"},
  "atmo_permafrost": {"name":"出土化石","desc":"在永冻星球上建立文明。","flair":"仍然栩栩如生。"},
  "atmo_retrograde": {"name":"逆流而上","desc":"在月球逆行星球上建立文明。","flair":"并不是与众不同的。"},
  "atmo_kamikaze": {"name":"玉石俱焚","desc":"在神风星球上建立文明。","flair":"需要准备更好的防晒措施了……"},
  "vigilante": {"name":"私人警察","desc":"在邪恶宇宙中，毁灭 12 个不同种族的文明。","flair":"头骨燃烧着的摩托骑士。"},
  "squished": {"name":"压瘪","desc":"在微型宇宙中被压碎。","flair":"当心脚下！"},
  "double_density": {"name":"双重密度","desc":"高引力宇宙中，在高密度星球上进行播种重置。","flair":"有人需要脊椎减压治疗吗？"},
  "cross": {"name":"不要穿越质粒","desc":"通过基因突变合成反质粒。","flair":"质子逆转？糟了……"},
  "macro": {"name":"宏观宇宙","desc":"在微型宇宙中，使用有 [矮小] 特质或 [袖珍] 特质的种族进行播种重置。","flair":"永远不要进入亚原子领域。"},
  "marble": {"name":"亚基伦银河系","desc":"在微型宇宙中，使用没有 [矮小] 特质和 [袖珍] 特质的种族进行播种重置。","flair":"你怎么知道自己不是生活在一颗更大一点的玻璃球里？"},
  "heavyweight": {"name":"重量级拳王","desc":"在高引力宇宙中，引领 8 个不同的种群进行播种重置。","flair":"谁也没法将你击倒读秒。"},
  "whitehole": {"name":"白洞","desc":"引爆黑洞，毁灭标准宇宙。","flair":"宇宙完蛋了，你满意了吗？"},
  "heavy": {"name":"太重了","desc":"使高引力宇宙毁于引力过大。","flair":"你们宇宙的引力有问题吗？"},
  "canceled": {"name":"抵消","desc":"使反物质宇宙毁于湮灭。","flair":"我是不是说过？ 别 让 它们相互接触！"},
  "eviltwin": {"name":"涤荡邪秽","desc":"摧毁邪恶宇宙。","flair":"终于可以跟这个充满渣滓和败类的宇宙说再见了。"},
  "microbang": {"name":"我也做过神","desc":"毁灭微型宇宙。","flair":"在每个人都死去之前你做的很不错。"},
  "pw_apocalypse": {"name":"真言术：启示录","desc":"毁灭魔法宇宙。","flair":"有些咒语之所以叫做禁咒是有原因的。"},
  "fullmetal": {"name":"全金属","desc":"转化出一种高级材料。","flair":"毁灭后再创造，这是宇宙的准则。"},
  "pass": {"name":"此路可通","desc":"在不修改炎魔特质的前提下，使宇宙毁于坍缩。","flair":"此路不通！除非……你一定要通过。"},
  "soul_sponge": {"name":"灵魂海绵","desc":"吸收足够的灵魂能量并进行飞升。","flair":"不必保留任何东西了。"},
  "nightmare": {"name":"远古梦魇","desc":"召唤远古梦魇。","flair":"恐怖就此开始。"},
  "escape_velocity": {"name":"逃离引力井","desc":"成功逃离引力井。","flair":"动作快一点！"},
  "what_is_best": {"name":"什么是最好的？","desc":"完成黑暗战神剧情模式。","flair":"击退敌人，看着他们跪地求饶的样子。"},
  "joyless": {"name":"无趣","desc":"无趣地定居到另一个星球上。","flair":"这是一个没有欢笑的世界。"},
  "steelen": {"name":"物美价廉","desc":"在不知道如何冶炼钢的情况下进行播种重置。","flair":"说真的，那是什么？"},
  "dissipated": {"name":"消散","desc":"毁灭衰变的宇宙。","flair":"反正放着不管它也要完蛋了。"},
  "technophobe": {"name":"技术恐惧症","desc":"在电子技术经常暴走的条件下进行飞升重置。","flair":"能量憎恨你，而你自己成为了能量，有趣吗？"},
  "wheelbarrow": {"name":"钱如废纸","desc":"在通货膨胀的条件下获得 250000M 资金。","flair":"是不是该考虑金圆券了？"},
  "iron_will": {"name":"钢铁意志","desc":"在大灾变中幸存下来。","flair":"没有什么能阻止你。"},
  "failed_history": {"name":"失败的轮回","desc":"再次引发大灾变。","flair":"吃一堑，而未长一智。"},
  "banana": {"name":"香蕉奶昔","desc":"完成香蕉共和国挑战。","flair":"从单一出口到统治世界。"},
  "pathfinder": {"name":"碳基黄昏","desc":"在智械黎明剧情模式中找到一条出路。","flair":"啊，留下一条路等改日再见！但我知道路径延绵无尽头，恐怕我难以再回返。"},
  "ashanddust": {"name":"尘归尘，土归土","desc":"在智械黎明剧情模式中进行核爆重置。","flair":"欢迎来到新纪元。"},
  "exodus": {"name":"出埃及记","desc":"在智械黎明剧情模式中进行播种重置。","flair":"这次可能远不止 40 年了。"},
  "obsolete": {"name":"淘汰","desc":"在智械黎明剧情模式中进行人工智能觉醒，使智械取而代之。","flair":"这次任务对我来说很重要，我不允许你去破坏。"},
  "bluepill": {"name":"蓝色胶囊","desc":"进入矩阵系统。","flair":"未知的幸福。"},
  "retired": {"name":"隐退","desc":"隐退并享受美好生活。","flair":"安详地度过晚年。"},
  "gross": {"name":"令人不适","desc":"使用拥有 [淤泥] 特质的非液体种族达到伟大。","flair":"黏糊糊的。"},
  "lamentis": {"name":"拉门蒂斯","desc":"在地月撞击时存活下来，然后重塑一个新的星球。","flair":"无路可走。"},
  "overlord": {"name":"主宰","desc":"使用所有 3 种方法征服沃姆林并进行 4 阶重置。","flair":"赞美星际之主。"},
  "adam_eve": {"name":"亚当与夏娃","desc":"在人口被限制为 1 的条件下，重新繁衍种族。","flair":"当心蛇出没。"},
  "endless_hunger": {"name":"无尽饥饿","desc":"完成全部禁食剧情模式的相关目标。","flair":"从今以后，我们不再需要吃东西来生存了。"},
};

export const FEAT_LOCALE: Record<string, AchievementLocaleText> = {
  "utopia": {"name":"乌托邦","desc":"将士气提升至 500%。","flair":"不要唤醒梦中人。"},
  "take_no_advice": {"name":"不听劝阻","desc":"在地狱星球上使用非恶魔种群进行核爆重置。","flair":"警告是给娘炮看的！纯爷们从不看警告！"},
  "ill_advised": {"name":"不理智","desc":"在地狱星球上使用非恶魔种群进行播种重置。","flair":"你在教我做事？"},
  "organ_harvester": {"name":"器官贩子","desc":"将基因灾难带上太空，并将他们的痛苦传向下一个星球。","flair":"你只是为了他们的身体组织，才创造了他们，对吧？"},
  "the_misery": {"name":"苦难","desc":"使用基因灾难，进行播种重置阶段之后的任意重置。","flair":"你应该知道你只需要核爆重置的吧？"},
  "energetic": {"name":"劲量","desc":"在不建造集热器的前提下，进行飞升重置。","flair":"永不疲倦，继续前进，前进，前进……"},
  "garbage_pie": {"name":"垃圾馅饼","desc":"在不修改特质的前提下，使用基因灾难进行飞升重置或恶魔灌注。","flair":"什么都不要，多放点洋葱。"},
  "finish_line": {"name":"越过终点线","desc":"在大灾变模式中进行飞升重置或恶魔灌注。","flair":"从容不迫，胜券在握。"},
  "blank_slate": {"name":"白板","desc":"移除所有种群特质和主修特质。","flair":"父亲在上，魂佑江东；公瑾在旁，智定天下！"},
  "supermassive": {"name":"超大质量","desc":"使用质量喷射器将黑洞质量扩充到 100 个太阳质量。","flair":"真的，也没那么超大。"},
  "steelem": {"name":"钢铁公爵","desc":"在没有学会冶炼钢的情况下摧毁一个宇宙。","flair":"不作死就不会死。"},
  "banana": {"name":"香蕉船","desc":"在香蕉共和国挑战中，出口 500 个资源并且进口 500 个资源。","flair":"香蕉你个芭乐！"},
  "rocky_road": {"name":"崎岖之路","desc":"在至少有 3 条矿产属性为匮乏的星球上进行播种重置。","flair":"不含冰淇淋。"},
  "demon_slayer": {"name":"斩妖除魔","desc":"击杀六亿六千六百万头恶魔。","flair":"他们是燃烧军团。"},
  "equilibrium": {"name":"平衡","desc":"让所有种族都加入多元宇宙。","flair":"完美的平衡，万物本该如此。"},
  "planned_obsolescence": {"name":"过时的计划","desc":"使用至少32个种族进行人工智能觉醒。","flair":"长江后浪推前浪，世上新人赶旧人。"},
  "digital_ascension": {"name":"机械飞升","desc":"使用合成人或纳米机器人，在不修改特质的前提下，在E.M.磁场模式中进行飞升重置。","flair":"我们不再只是冷冰冰的机器了。"},
  "grand_death_tour": {"name":"超级死亡之旅","desc":"通过6种不同的方式结束终极软泥的痛苦。","flair":"它就是干不掉。"},
  "novice": {"name":"新手的足迹","desc":"获得 10 个成就。","flair":"你死于痢疾。"},
  "journeyman": {"name":"基因熟练工","desc":"获得 25 个成就。","flair":"你涉水过河，丢了两头牛。"},
  "adept": {"name":"专家","desc":"获得 50 个成就。","flair":"这一带的游戏你全玩完了。"},
  "master": {"name":"进化大师","desc":"获得 75 个成就。","flair":"沿哥伦比亚河顺流而下。"},
  "grandmaster": {"name":"命运宗师","desc":"获得 100 个成就。","flair":"恭喜！你成功了！"},
  "god": {"name":"进化之神","desc":"获得 150 个成就。","flair":"别被冲昏头脑了！"},
  "nephilim": {"name":"奈非天","desc":"使用天堂种族摧毁邪恶宇宙。","flair":"没有奶牛关。"},
  "twisted": {"name":"扭曲","desc":"成为堕入黑暗的天堂种族。","flair":"我们每个人都有罪。"},
  "slime_lord": {"name":"史莱姆王","desc":"将最卑微的生物提升为大恶魔。","flair":"我不是邪恶的史莱姆哟！"},
  "annihilation": {"name":"湮灭","desc":"用反物质爆炸把自己炸飞。","flair":"没有人告诉过您物质和反物质不能相容吗？"},
  "immortal": {"name":"不朽的秘密","desc":"在禁食剧情模式且在没有市民饿死的前提下，烹饪“食物”。","flair":"跳出三界外，不在五行中！"},
  "wish": {"name":"参与奖","desc":"许下伟大的愿望。","flair":"你感觉到有什么不凡的了吗？"},
  "friday": {"name":"水晶湖","desc":"有人在黑色星期五溺毙了。","flair":"真不该靠近那个湖的……"},
  "valentine": {"name":"放置情人节","desc":"在情人节充满爱地放置你的文明。","flair":"连花都没送！"},
  "leprechaun": {"name":"不幸","desc":"放置时一个小妖精偷走了你的黄金。","flair":"幸好黄金不是资源。"},
  "easter": {"name":"跳跳兔","desc":"一只兔子绕着无所事事的你蹦蹦跳跳。","flair":"找到所有糖果了吗？"},
  "egghunt": {"name":"猎蛋行动","desc":"在复活节活动期间至少找到 12 个隐藏彩蛋。","flair":"希望你在蛋发臭前找到它们。"},
  "launch_day": {"name":"游戏发布纪念日","desc":"在游戏发布纪念日期间放置你的文明。","flair":"飞向宇宙，浩瀚无垠！"},
  "solstice": {"name":"夏至篝火狂欢","desc":"在夏至篝火狂欢活动期间燃烧一百万单位铝热剂。","flair":"为什么我的手中多了火把和汽油？"},
  "firework": {"name":"烟花狂欢","desc":"在烟花狂欢活动期间开启烟花厂。","flair":"轰！"},
  "halloween": {"name":"血溅万圣劫","desc":"在万圣节期间放置你的文明。","flair":"该找谁帮忙？"},
  "trickortreat": {"name":"不给糖就捣蛋！","desc":"在万圣节活动期间至少找到合计 12 个糖果和幽灵。","flair":"玉米糖太难吃了！"},
  "thanksgiving": {"name":"狼吞虎咽","desc":"在感恩节期间放置你的文明。","flair":"差不多该餐后困倦了……"},
  "xmas": {"name":"吼！吼！吼！","desc":"在圣诞节期间放置你的文明。","flair":"救命！我被卡在烟囱里了！"},
  "fool": {"name":"愚蠢的土拨鼠！","desc":"你的成就令人折服！","flair":"愚人节快乐！"},
};
