/**
 * @evozen/game-core
 * 纯逻辑模块，不含任何 DOM / UI 依赖
 */

export { createNewGame, defaultSettings } from './state';
export { seededRandom, mathRand } from './random';
export {
  getBuildCost,
  canBuildStructure,
  buildStructure,
  manualGather,
  buildSpaceStructure,
  buildInterstellarStructure,
  enqueueStructure,
  dequeueStructure,
  isTechAvailable,
  getResearchCost,
  canResearchTech,
  researchTech,
  assignWorker,
  removeWorker,
  setTaxRate,
  assignFactoryLine,
  removeFactoryLine,
  assignMiningDroid,
  removeMiningDroid,
  assignSmelter,
  removeSmelter,
  type FactoryLineId,
  type MiningDroidTargetId,
} from './actions';
export {
  SPACE_STRUCTURES,
  canBuildSpaceStructure,
  getSpaceBuildCost,
  getSatelliteCount,
  getSatelliteKnowledgeCapBonus,
  getSatelliteScientistImpactMultiplier,
  getSatelliteWardenclyffeMultiplier,
  getPropellantDepotCount,
  getPropellantDepotOilCapBonus,
  getPropellantDepotHeliumCapBonus,
  getGpsCount,
  getGpsTradeRouteBonus,
  getMoonBaseCount,
  getMoonBaseIridiumCapBonus,
  getHeliumMineHeliumCapBonus,
  getObservatoryCount,
  getObservatoryKnowledgeCapBonus,
  zigguratBonus,
  getSpaceBarracksSoldiers,
  SPACE_BARRACKS_OIL_PER_TICK,
  SPACE_BARRACKS_FOOD_PER_TICK,
  getExoticLabKnowledgeCapBonus,
  type SpaceStructureDefinition,
  type SpaceCostFunction,
  type SupportPool,
} from './space';
export {
  INTERSTELLAR_STRUCTURES,
  getInterstellarBuildCost,
  canBuildInterstellarStructure,
  resolveInterstellarSupport,
  type InterstellarStructureDefinition,
  type InterstellarSupportPool,
  type InterstellarSupportResult,
} from './interstellar';
export {
  SPACE_ACTIONS,
  getSpaceActionCost,
  canRunSpaceAction,
  runSpaceAction,
  type SpaceActionDefinition,
} from './space-actions';
export {
  resolveSpaceSupport,
  listSpacePowerConsumers,
  type SpaceSupportResult,
} from './space-support';
export { RESOURCE_VALUES, TRADE_RATIOS, CRAFT_COSTS, type CraftRecipe } from './resources';
export { BASE_JOBS, type JobDefinition } from './jobs';
export { BASIC_TECHS, type TechDefinition } from './tech';
export { BASIC_STRUCTURES, type StructureDefinition, type CostFunction } from './structures';
export {
  SPECIES_TRAITS,
  SPECIES_TRAIT_DESCRIPTORS,
  assignSpeciesTraits,
  getSpeciesTraitDescriptors,
  getProfessorTraitBonus,
  getLibraryKnowledgeCapMultiplier,
  getTradeBuyPriceMultiplier,
  getTradeSellPriceMultiplier,
  getTaxIncomeTraitMultiplier,
  getCraftingSpeedMultiplier,
  getScienceKnowledgeCostMultiplier,
  getModifiedTechCosts,
  getTrainingSpeedDivisor,
  getBruteTrainingBonus,
  getMercCostMultiplier,
  getHungerMultiplier,
  type SupportedSpeciesId,
  type SpeciesTraitId,
  type SpeciesTraitDescriptor,
} from './traits';
export { gameTick, factoryTick } from './tick';
export { saveGame, loadGame, exportSave, importSave } from './save';
export * from './commerce';
export * from './espionage';
export {
  manualCraft,
  craftingTick,
  craftingTickWithSupport,
  assignCraftsman,
  removeCraftsman,
  CRAFTABLE_IDS,
  type CraftableId,
  type FoundryState,
} from './crafting';
export type { FactoryState } from '@evozen/shared-types';
export {
  buyResource,
  sellResource,
  getBuyPrice,
  getSellPrice,
  getManualTradeLimit,
  tradeTick,
  getMaxTradeRoutes,
  getTradeRouteQtyLimit,
  setTradeRoute,
  TRADABLE_RESOURCES,
  type TradeRoute,
  type TradableResourceId,
} from './trade';
export {
  GOVERNMENT_DEFS,
  changeGovernment,
  getGovernmentChangeCooldown,
  getTaxMultiplier,
  getProductionMultiplier,
  getMaxTaxRate,
  getTempleMultiplier,
  getKnowledgeMultiplier,
  getBankerImpactMultiplier,
  getCasinoIncomeMultiplier,
  getTourismIncomeMultiplier,
  getFactoryOutputMultiplier,
  type GovernmentType,
  type GovernmentDef,
} from './government';
export {
  getQueueMax,
  canEnqueue,
  isQueueUnlocked,
  toggleQueueMode,
} from './queue';
export {
  buildCrate,
  buildContainer,
  assignCrate,
  unassignCrate,
  assignContainer,
  unassignContainer,
  getTotalAssignedCrates,
  getTotalAssignedContainers,
  getStorageBonus,
  getStorageMultiplier,
  SHED_BASE_VALUES,
  BASE_CRATE_VALUE as CRATE_VALUE,
  CONTAINER_VALUE,
  getCrateValue,
  getContainerValue,
  CRATE_COST_PLYWOOD,
  CONTAINER_COST_STEEL,
  STORABLE_RESOURCES,
  type StorableResourceId,
} from './storage';
export {
  calculateMorale,
  randomizeWeather,
  type MoraleResult,
} from './morale';
export {
  powerTick,
  listPowerGenerators,
  listPowerConsumers,
  isPoweredBuilding,
  type PowerGeneratorDef,
  type PowerConsumerDef,
  type PowerTickResult,
} from './power';
export {
  weaponTechModifier,
  armyRating,
  armorCalc,
  tickTraining,
  tickHealing,
  mercCost,
  hireMerc,
  warCampaign,
  garrisonSize,
  TACTIC_NAMES,
  type WarResult,
} from './military';
export {
  tickEvents,
  EVENTS,
  type EventDefinition,
} from './events';
export {
  applyDerivedState,
  applyDerivedStateInPlace,
} from './derived-state';
export {
  applySimulationDerivedState,
  applySimulationDerivedStateInPlace,
  handlePopulationGrowth,
  runSimulationTick,
  simulateTicks,
  createDeterministicRandom,
  type SimulationTickOptions,
  type SimulationRunResult,
} from './simulation';
export {
  PLANET_TRAITS,
  hasPlanetTrait,
  getPlanetTrait,
  getMinerPlanetMultiplier,
  getGlobalPlanetMultiplier,
  getFarmPlanetMultiplier,
  type PlanetTraitDef,
} from './planet-traits';
export {
  EVO_UPGRADES,
  EVO_STEPS,
  EVO_RACES,
  evolutionTick,
  purchaseEvoUpgrade,
  advanceEvoStep,
  evolveSentience,
  getAvailableUpgrades,
  getAvailableSteps,
  getAvailableRaces,
  getUpgradeCount,
  getUpgradeCost,
  type EvoUpgrade,
  type EvoStep,
  type EvoRace,
} from './evolution';
export {
  ARPA_PROJECTS,
  MONUMENT_NAMES,
  arpaCost,
  arpaTick,
  isArpaAvailable,
  startArpaProject,
  stopArpaProject,
  setMonumentType,
  getArpaProjectState,
  getMonumentType,
  getAvailableArpaProjects,
  getMonumentMoraleBonus,
  type ArpaProjectDef,
  type ArpaProjectState,
  type ArpaState,
  type MonumentType,
} from './arpa';
export {
  triggerReset,
  canReset,
  resetMAD,
  resetBioseed,
  resetCataclysm,
  resetBlackhole,
  resetAscend,
  resetDescend,
  resetApotheosis,
  resetRetire,
  resetTerraform,
  resetAiApocalypse,
  resetMatrix,
  resetGardenOfEden,
  calcPrestigeGains,
  type ResetType,
  type PrestigeGains,
} from './resets';
export {
  UNIVERSES,
  applyUniverse,
  getCurrentPrestigeType,
  getUniverseDifficultyMul,
  type UniverseType,
  type UniverseDefinition,
} from './bigbang';
export {
  saveCustomRace,
  loadCustomRace,
  clearCustomRace,
  calcCustomRaceBalance,
  validateCustomRace,
  applyCustomRace,
  type CustomRaceConfig,
} from './custom-race';
export {
  getPet,
  spawnPet,
  petTick,
  getPetMoraleBonus,
  removePet,
  getPetInteractionText,
  type PetType,
  type PetState,
} from './pet';
export {
  applyMaterialSubstitution,
  shouldHideResource,
} from './material-substitution';
export {
  applyImitationTraits,
  getSelenophobiaMultiplier,
  isEnvironmentalist,
  getEnvironmentalistRenewableBonus,
  getElementalType,
  getElementalBonus,
  getImitatedSpecies,
  processBlubber,
  getTuskMiningBonus,
  tryRevive,
  processUnstableDeath,
  getCannibalismBonus,
  getDeconstructorCostMul,
  getLinkedQuantiumBonus,
  getShapeshifterPositiveRank,
  getShapeshifterNegativeRank,
  isWishReady,
  makeWish,
  type WishReward,
  getOcularPowers,
  isForgeSmelting,
  isCataclysmRace,
  complexTraitTick,
  type ElementalType,
} from './complex-traits';
export {
  applySludgeTraits,
  applyJunkerTraits,
  applyNephilimTraits,
  applyHellspawnTraits,
  applyUltraSludgeTraits,
  applySpecialRaceTraits,
} from './special-races';
export {
  GENUS_DEFS,
  RACES,
  getRacesByGenus,
  getAvailableBasicRaces,
  getRaceFullTraits,
  applyRaceTraits,
  NEGATIVE_TRAITS,
  isNegativeTrait,
  type GenusId,
  type GenusDefinition,
  type RaceId,
  type RaceDefinition,
} from './races';
export {
  TRAITS,
  traitRank,
  isPositiveTrait,
  getGenusTraits,
  getMajorTraits,
  getMinorTraits,
  getTraitsByOrigin,
  type TraitDefinition,
  type TraitType,
  type TraitTaxonomy,
} from './trait-data';
export {
  TRAIT_RANKS,
  getTraitRanks,
  getTraitVar,
  attachAllRanks,
  type RankKey,
} from './trait-ranks';
export {
  defaultWomlingState,
  initWomling,
  discoverWomling,
  getWomlingPopCap,
  assignWomling,
  womlingTick,
  canUseWomling,
  type WomlingState,
} from './womling';
export {
  calcSyndicatePressure,
  syndicateTick,
  siegeTick,
  piracy,
} from './syndicate';
export {
  getSpireFloorRating,
  getSpireFloorReward,
  attemptSpireFloor,
  getCurrentSpireInfo,
  getFloorEnemy,
  getEffectivePlayerRating,
  SPIRE_ENEMIES,
  type SpireAscendResult,
  type SpireEnemyType,
  type SpireEnemyDef,
} from './spire';
export {
  mechRating,
  mechRatingInTerrain,
  isChassisCompatible,
  mechCost,
  mechSize,
  getMechBayCapacity,
  initMechState,
  startMechBuild,
  mechBuildTick,
  mechStationPatrolTick,
  setPatrolMode,
  getPatrolMode,
  totalMechRating,
  damageMechs,
  type MechDef,
  type MechState,
  type MechSize,
  type MechChassis,
  type MechWeapon,
  type MechEquipment,
} from './mech';
export {
  checkAchievements,
  checkResetAchievements,
} from './achievement-triggers';
export {
  CRISPR_UPGRADES,
  getCrisprLevel,
  canPurchaseCrispr,
  purchaseCrispr,
  isCrisprUnlocked,
  getAvailableCrispr,
  getDiscoveredMinorTraits,
  rollMinorTrait,
  type CrisprUpgrade,
} from './crispr';
export {
  ACHIEVEMENTS,
  ACHIEVE_LIST,
  FEATS,
  getChallengeLevel,
  getUniverseAffix,
  calcUniverseLevel,
  unlockAchievement,
  unlockFeat,
  hasAchievement,
  getAchievementLevel,
  countAchievements,
  calcMastery,
  checkAchievementHunterFeats,
  type AchievementCategory,
  type AchievementDefinition,
  type AchievementRecord,
  type FeatDefinition,
} from './achievements';
export {
  GOVERNOR_BACKGROUNDS,
  GOVERNOR_TRAITS,
  GOVERNOR_TASKS,
  GOVERNOR_NAMES,
  generateGovernorCandidates,
  appointGovernor,
  fireGovernor,
  govActive,
  getTaskSlotCount,
  setGovernorTask,
  runGovernorTasks,
  type GovernorBackgroundId,
  type GovernorBackgroundDef,
  type GovernorTraitDef,
  type GovernorTaskId,
  type GovernorTaskDef,
  type GovernorCandidate,
  type GovernorTasks,
  type GovernorState,
} from './governor';
export {
  PORTAL_REGIONS,
  PORTAL_BUILDINGS,
  defaultFortressState,
  fortressTick,
  portalProductionTick,
  tunePillar,
  getTunedPillarCount,
  getPillarBonus,
  calcSoulGemProgress,
  defaultSpireState,
  ascendSpire,
  getBuildingsByRegion,
  isRegionUnlocked,
  isBuildingVisible,
  getPortalBuildCost,
  canBuildPortalStructure,
  buildPortalStructure,
  type PortalRegionId,
  type PortalRegionDef,
  type PortalBuildingDef,
  type FortressState,
  type SpireState,
} from './portal';
export {
  EDENIC_REGIONS,
  EDENIC_BUILDINGS,
  edenicProductionTick,
  isEdenicUnlocked,
  isEdenicRegionUnlocked,
  isAsphodelHostile,
  getEdenicBuildingsByRegion,
  getEdenicBuildCost,
  canBuildEdenic,
  buildEdenicStructure,
  edenicTick,
  type EdenicRegionId,
  type EdenicRegionDef,
  type EdenicBuildingDef,
} from './edenic';
export {
  TRUEPATH_REGIONS,
  TRUEPATH_BUILDINGS,
  truepathProductionTick,
  isTruepath,
  isTruepathRegionUnlocked,
  getSyndicatePressure,
  canRetire,
  getTruepathBuildingsByRegion,
  getTruepathBuildCost,
  canBuildTruepath,
  buildTruepathStructure,
  type TruepathRegionId,
  type TruepathRegionDef,
  type TruepathBuildingDef,
} from './truepath';
export {
  RITUAL_TYPES,
  ALCHEMY_RESOURCES,
  setupRituals,
  cancelRituals,
  setRitualPower,
  getRitualMultiplier,
  setupAlchemy,
  setAlchemyTarget,
  alchemyTick,
  getAstrologySign,
  getAstrologyValue,
  unlockBloodPact,
  performBloodSacrifice,
  conjureFood,
  buildShrine,
  getShrineBonus,
  isMagicUniverse,
  magicTick,
  type RitualType,
  type RitualCastingState,
  type AlchemyResource,
  type ZodiacSign,
  type BloodPactState,
  type ShrineState,
} from './magic';
