/**
 * 基础科技树定义
 * 从旧 src/tech.js 提取第一阶段的基础科技
 */

export interface TechDefinition {
  id: string;
  name: string;
  description: string;
  category: string;
  era: string;
  /** 前置科技要求 */
  reqs: Record<string, number>;
  /** 解锁授予的科技: [key, level] */
  grant: [string, number];
  /** 费用 */
  costs: Record<string, number>;
  /** 解锁后的效果描述 */
  effect: string;
}

/** 第一阶段基础科技 */
export const BASIC_TECHS: TechDefinition[] = [
  // ===== 原始时代 =====
  {
    id: 'club',
    name: '棍棒',
    description: '用来捕猎的原始武器。',
    category: 'hunting',
    era: '原始',
    reqs: {},
    grant: ['primitive', 1],
    costs: { Lumber: 5 },
    effect: '解锁骨制工具的研究。',
  },
  {
    id: 'bone_tools',
    name: '骨制工具',
    description: '由骨头制成的基本工具。',
    category: 'tools',
    era: '原始',
    reqs: { primitive: 1 },
    grant: ['primitive', 2],
    costs: { Food: 10, Lumber: 10 },
    effect: '解锁石工岗位和石头采集。',
  },
  {
    id: 'sundial',
    name: '日晷',
    description: '通过观测太阳位置来计时。',
    category: 'science',
    era: '原始',
    reqs: { primitive: 2 },
    grant: ['primitive', 3],
    costs: { Lumber: 8, Stone: 10 },
    effect: '解锁知识系统和日历，开启文明时代科技。',
  },

  // ===== 文明时代 =====
  {
    id: 'axe',
    name: '石斧',
    description: '用石头制成的简易斧头。',
    category: 'tool',
    era: '文明',
    reqs: { primitive: 2 },
    grant: ['axe', 1],
    costs: { Stone: 5, Food: 5 },
    effect: '解锁伐木工岗位和伐木场建筑。',
  },
  {
    id: 'housing',
    name: '住房',
    description: '为市民提供住所。',
    category: 'housing',
    era: '文明',
    reqs: { primitive: 3 },
    grant: ['housing', 1],
    costs: { Knowledge: 10 },
    effect: '解锁小屋建筑，人口可以增长。',
  },
  {
    id: 'cottage_tech',
    name: '建筑学',
    description: '学习更先进的房屋建造。',
    category: 'housing',
    era: '文明',
    reqs: { housing: 1, science: 1 },
    grant: ['housing', 2],
    costs: { Knowledge: 250 },
    effect: '解锁茅屋建筑，每座提供 +2 人口上限。',
  },
  {
    id: 'agriculture',
    name: '农业',
    description: '学习系统性种植作物。',
    category: 'agriculture',
    era: '文明',
    reqs: { primitive: 3 },
    grant: ['agriculture', 1],
    costs: { Knowledge: 10 },
    effect: '解锁农场建筑和农民岗位。',
  },
  {
    id: 'irrigation',
    name: '灌溉',
    description: '引水灌溉农田。',
    category: 'agriculture',
    era: '文明',
    reqs: { agriculture: 1 },
    grant: ['agriculture', 2],
    costs: { Knowledge: 40 },
    effect: '农民产量 +40%。',
  },
  {
    id: 'silo_tech',
    name: '储粮技术',
    description: '学习大量储存粮食。',
    category: 'storage',
    era: '文明',
    reqs: { agriculture: 2 },
    grant: ['agriculture', 3],
    costs: { Knowledge: 80 },
    effect: '解锁粮仓建筑。',
  },
  {
    id: 'mill_tech',
    name: '磨坊技术',
    description: '利用风力磨碎谷物。',
    category: 'food',
    era: '文明',
    reqs: { agriculture: 3 },
    grant: ['agriculture', 4],
    costs: { Knowledge: 200 },
    effect: '解锁磨坊建筑，食物产量 +5%。',
  },
  {
    id: 'mining',
    name: '采矿',
    description: '学习从地下开采矿物。',
    category: 'mining',
    era: '文明',
    reqs: { primitive: 3, axe: 1 },
    grant: ['mining', 1],
    costs: { Knowledge: 45 },
    effect: '解锁采石场建筑和石工效率加成。',
  },
  {
    id: 'mining_2',
    name: '深层采矿',
    description: '向更深层挖掘。',
    category: 'mining',
    era: '文明',
    reqs: { mining: 1 },
    grant: ['mining', 2],
    costs: { Knowledge: 120 },
    effect: '解锁矿井建筑和矿工岗位。',
  },
  {
    id: 'mining_3',
    name: '铁器冶炼',
    description: '学习冶炼铁矿石。',
    category: 'mining',
    era: '文明',
    reqs: { mining: 2 },
    grant: ['mining', 3],
    costs: { Knowledge: 500 },
    effect: '矿工可以挖铁矿。铁矿显示。',
  },
  {
    id: 'mining_4',
    name: '煤炭开采',
    description: '从地层深处开采煤炭。',
    category: 'mining',
    era: '文明',
    reqs: { mining: 3, science: 1 },
    grant: ['mining', 4],
    costs: { Knowledge: 1500 },
    effect: '解锁煤矿和煤矿工人。煤炭显示。',
  },
  {
    id: 'science',
    name: '科学方法',
    description: '系统化研究万物。',
    category: 'science',
    era: '文明',
    reqs: { primitive: 3 },
    grant: ['science', 1],
    costs: { Knowledge: 65 },
    effect: '解锁图书馆建筑和教授岗位。',
  },
  {
    id: 'cement',
    name: '水泥',
    description: '学习制造水泥。',
    category: 'cement',
    era: '文明',
    reqs: { mining: 1, science: 1 },
    grant: ['cement', 1],
    costs: { Knowledge: 500 },
    effect: '解锁水泥厂和水泥工人。水泥显示。',
  },
  {
    id: 'currency',
    name: '货币',
    description: '建立统一的货币体系。',
    category: 'commerce',
    era: '文明',
    reqs: { primitive: 3 },
    grant: ['currency', 1],
    costs: { Knowledge: 22 },
    effect: '解锁金币和基础税收。',
  },
  {
    id: 'banking_tech',
    name: '银行业',
    description: '建立金融和借贷体系。',
    category: 'commerce',
    era: '文明',
    reqs: { currency: 1, science: 1 },
    grant: ['banking', 1],
    costs: { Knowledge: 450 },
    effect: '解锁银行建筑和银行家岗位。',
  },
  {
    id: 'military',
    name: '军事',
    description: '组建军事力量。',
    category: 'military',
    era: '文明',
    reqs: { primitive: 3 },
    grant: ['military', 1],
    costs: { Knowledge: 40 },
    effect: '解锁兵营和士兵。',
  },
  {
    id: 'trade',
    name: '贸易',
    description: '建立贸易路线。',
    category: 'commerce',
    era: '文明',
    reqs: { currency: 1, military: 1 },
    grant: ['trade', 1],
    costs: { Knowledge: 720 },
    effect: '解锁贸易站。',
  },
  {
    id: 'storage',
    name: '储存',
    description: '建造更好的仓库系统。',
    category: 'storage',
    era: '文明',
    reqs: { primitive: 3, currency: 1 },
    grant: ['container', 1],
    costs: { Knowledge: 65 },
    effect: '解锁仓库建筑和板条箱。',
  },
];
